package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, November 8, 2019 8:24:47 PM PST
*/

public interface HelloOperations 
{
  void slay (String someText);
  String respawn ();
  void shutdown ();
} // interface HelloOperations
