package mserver;


/**
* mserver/recollectorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/thisi/Desktop/tareas/Java/corba-interfc/src/main/java/Recollector.idl
* Monday, October 28, 2019 2:33:08 PM PDT
*/

public abstract class recollectorPOA extends org.omg.PortableServer.Servant
 implements mserver.recollectorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("undo", new java.lang.Integer (0));
    _methods.put ("keep", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // mserver/recollector/undo
       {
         String $result = null;
         $result = this.undo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // mserver/recollector/keep
       {
         String description = in.read_string ();
         String category = in.read_string ();
         this.keep (description, category);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:mserver/recollector:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public recollector _this() 
  {
    return recollectorHelper.narrow(
    super._this_object());
  }

  public recollector _this(org.omg.CORBA.ORB orb) 
  {
    return recollectorHelper.narrow(
    super._this_object(orb));
  }


} // class recollectorPOA
