package mserver;


/**
* mserver/recollectorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/thisi/Desktop/tareas/Java/corba-interfc/src/main/java/Recollector.idl
* Monday, October 28, 2019 2:33:09 PM PDT
*/

public interface recollectorOperations 
{
  String undo ();
  void keep (String description, String category);
} // interface recollectorOperations
