package mserver;

/**
* mserver/recollectorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/thisi/Desktop/tareas/Java/corba-interfc/src/main/java/Recollector.idl
* Monday, October 28, 2019 2:33:09 PM PDT
*/

public final class recollectorHolder implements org.omg.CORBA.portable.Streamable
{
  public mserver.recollector value = null;

  public recollectorHolder ()
  {
  }

  public recollectorHolder (mserver.recollector initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mserver.recollectorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mserver.recollectorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mserver.recollectorHelper.type ();
  }

}
