package mserver;


/**
* mserver/recollector.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/thisi/Desktop/tareas/Java/corba-interfc/src/main/java/Recollector.idl
* Monday, October 28, 2019 2:33:09 PM PDT
*/

public interface recollector extends recollectorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface recollector
